### ISSUE TITLE
Use generators

### ISSUE THREAD

**Issue by shlub** [neopoly/neo-rails#4]
Add generators with default structure to create Presenters/Mocks along with test classes.
Maybe add a hook to "rails g model" to automatically create presenter or mocks.
E.G: "rails g model User --presenter --mock username:string"

**Comment by splattael** [comment]
Closing == no?

**Comment by shlub** [comment]
This is already done.
See https://github.com/neopoly/neo-rails/commit/e919bb8fa43d38db7f2f9680cf05b94d716da22f and later
